FROM node:slim


WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm install --no-optional && npm cache clean --force

COPY index.js /app/

EXPOSE 3000
VOLUME ["/app/data"]

ENTRYPOINT ["node", "index.js"]