apiVersion: apps/v1
kind: Deployment
metadata:
  name: faust-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faust-consumer
  template:
    metadata:
      labels:
        app: faust-consumer
    spec:
      containers:
        - name: faust
          image: silasschroeder/stream-processing:0.9
          imagePullPolicy: Always
